services:
  zookeeper1:
      image: confluentinc/cp-zookeeper:7.0.1
      container_name: zookeeper1
      ports:
        - "2181:2181"
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_SERVER_ID: 1
        ZOOKEEPER_SERVERS: server.1=zookeeper1:2888:3888,server.2=zookeeper2:2888:3888,server.3=zookeeper3:2888:3888
      volumes:
        - ./zookeeper1/data:/var/lib/zookeeper/data
        - ./zookeeper1/log:/var/lib/zookeeper/log
      networks:
        - kafka-network

  zookeeper2:
      image: confluentinc/cp-zookeeper:7.0.1
      container_name: zookeeper2
      ports:
        - "2182:2181"
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_SERVER_ID: 2
        ZOOKEEPER_SERVERS: server.1=zookeeper1:2888:3888,server.2=zookeeper2:2888:3888,server.3=zookeeper3:2888:3888
      volumes:
        - ./zookeeper2/data:/var/lib/zookeeper/data
        - ./zookeeper2/log:/var/lib/zookeeper/log
      networks:
        - kafka-network

  zookeeper3:
      image: confluentinc/cp-zookeeper:7.0.1
      container_name: zookeeper3
      ports:
        - "2183:2181"
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_SERVER_ID: 3
        ZOOKEEPER_SERVERS: server.1=zookeeper1:2888:3888,server.2=zookeeper2:2888:3888,server.3=zookeeper3:2888:3888
      volumes:
        - ./zookeeper3/data:/var/lib/zookeeper/data
        - ./zookeeper3/log:/var/lib/zookeeper/log
      networks:
        - kafka-network

  kafka:
      image: confluentinc/cp-kafka:7.0.1
      container_name: kafka
      ports:
        - "9092:9092"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
        KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      depends_on:
        - zookeeper1
        - zookeeper2
        - zookeeper3
      networks:
        - kafka-network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: kafka_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kafka-network

  orders-service:
    build:
      context: ./orders-service
    container_name: orders-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/kafka_db
      SPRING_DATASOURCE_USERNAME:
      SPRING_DATASOURCE_PASSWORD:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - postgres
      - kafka
    networks:
      - kafka-network

  payment-service:
    build:
      context: ./payment-service
    container_name: payment-service
    ports:
      - "8082:8082"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka-network

  shipping-service:
    build:
      context: ./shipping-service
    container_name: shipping-service
    ports:
      - "8083:8083"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka-network

  notifications-service:
    build:
      context: ./notifications-service
    container_name: notifications-service
    ports:
      - "8084:8084"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka-network

volumes:
  postgres_data:

networks:
  kafka-network:
    name: kafka-network